### PR TITLE
Fix plotly dependencies

### PR DESCRIPTION
**Pull request by Alanocallaghan**
Address #6

### CODE REVIEW

**Comment by AliciaSchep** [comment]
Thanks @Alanocallaghan for noticing and fixing this issue! 

One issue I am noticing though with new plotly + this patch is that in an rmarkdown only the first plot  made by iheatmapr shows up in the html.  However, if a regular plotly plot is added as well, then all the plots show up...

**Comment by Alanocallaghan** [comment]
If you post an example I'll look into it

**Comment by AliciaSchep** [comment]
The vignette is an example -- adding `plotly::plot_ly(x =1:5,y=1:5)`  in a chunk anywhere in the document seems to make the problem go away

**Comment by Alanocallaghan** [comment]
Bizarre! A workaround would be to put that in a block starting `{r, echo=FALSE}` but that's not a great fix

**Comment by AliciaSchep** [comment]
It seems like adding in the additional dependencies that plotly r package uses, in particular  `crosstalk::crosstalkLibs()` is necessary for multiple iheatmapr plots to show up in rmarkdown.  Adding a plotly plot was a fix because the html would load those libraries.

**Comment by AliciaSchep** [comment]
Hi @Alanocallaghan, I decided to address the problem a different way, by removing the dependency on plotly r package in order to have more control over things like the version of plotly.js and other aspects of making the htmlwidget (as outlined in #7).  I'm going to close this pull request and the corresponding issue.  Thanks again for detecting this problem and suggesting a fix!

**Pull request closed without merging**
